### ISSUE TITLE
loginpage 입력 창

### ISSUE THREAD

**Issue by huir0** [9weeks-app-web/Team-5#9]
![스크린샷 2023-12-29 오후 3 15 52](https://github.com/9weeks-app-web/Team-5/assets/128926390/cfa18516-7c26-49d1-b707-67f7603b0e66)
이메일이랑 패스워드 입력하면 이렇게 칸이 작아집니다. 그리고 에러메세지가 아래에 뜨네요..

**Comment by seongbe** [comment]
![image](https://github.com/9weeks-app-web/Team-5/assets/122137973/5edd1960-45b8-430c-9eb5-e8fa9bdb8740)

**Comment by seongbe** [comment]
해결했습니다..!
